group :test do
  gem "rspec"
  gem "capybara"

  source "source_1" do
    gem "web-console"
    gem "annotate"
  end
end

gem "zeitwerk"
gem "rails"
gem "awesome_print"

group :development do
  gem "selenium-webdriver"
end
