source "source_1" do
  gem "rspec"
  gem "capybara"
end

source "source_2" do
  gem "web-console"
  gem "annotate"
end

gem "zeitwerk"
gem "rails"
gem "awesome_print"

source "source_1" do
  gem "selenium-webdriver"
end
